# Generated by Django 4.2.6 on 2023-10-11 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('specialization', models.CharField(choices=[('service-technician', 'Service-Technician'), ('brake-transmission-mechanic', 'Brake-Transmission-Mechanic'), ('general-mechanic', 'General-Mechanic'), ('diesel-mechanic', 'Diesel-Mechanic'), ('electro-mechanic', 'Electro-Mechanic'), ('body-mechanic', 'Body-mechanic'), ('office', 'Office')], max_length=27)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('profile', models.ImageField(null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
